import { NetworkAddressMap } from "./types";

export const DEPLOYER = ""; // for testnet, need to redeploy
export const CONTRACT_NAME = "aibtcdev-aibtc"; // for testnet, need to redeploy
export const TOKEN_CONTRACT_NAME = "aibtc-token"; // for testnet, need to redeploy

export const ADDRESSES: NetworkAddressMap = {
  mainnet: {
    BURN_ADDRESS: "SP000000000000000000002Q6VF78",
    STXCITY_SWAP_FEE_ADDRESS: "SP1WRH525WGKZJDCY8FSYASWVNVYB62580QNARMXP", 
    STXCITY_COMPLETE_FEE_ADDRESS: "SP1JYZFESCWMGPWQR4BJTDZRXTHTXXYFEVJECNTY7", 
    STXCITY_TOKEN_DEPLOYMENT_FEE_ADDRESS: "SP11WRT9TPPKP5492X3VE81CM1T74MD13SPFT527D", 
    STXCITY_DEX_DEPLOYMENT_FEE_ADDRESS: "SP1WG62TA0D3K980WGSTZ0QA071TZD4ZXNKP0FQZ7", 
    BITFLOW_CORE_ADDRESS: "SM1793C4R5PZ4NS4VQ4WMP7SKKYVH8JZEWSZ9HCCR.xyk-core-v-1-2", 
    BITFLOW_STX_TOKEN_ADDRESS: "SM1793C4R5PZ4NS4VQ4WMP7SKKYVH8JZEWSZ9HCCR.token-stx-v-1-2",
    BITFLOW_FEE_ADDRESS: "SP31C60QVZKZ9CMMZX73TQ3F3ZZNS89YX2DCCFT8P",
  },
  testnet: {
    BURN_ADDRESS: "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR",
    STXCITY_SWAP_FEE_ADDRESS: "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR",
    STXCITY_COMPLETE_FEE_ADDRESS: "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR",
    STXCITY_TOKEN_DEPLOYMENT_FEE_ADDRESS: "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR",
    STXCITY_DEX_DEPLOYMENT_FEE_ADDRESS: "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR",
    BITFLOW_CORE_ADDRESS: "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR.xyk-core-v-1-2",
    BITFLOW_STX_TOKEN_ADDRESS: "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR.token-stx-v-1-2",
    BITFLOW_FEE_ADDRESS: "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR",
  },
  devnet: {
    BURN_ADDRESS: "",
    STXCITY_SWAP_FEE_ADDRESS: "",
    STXCITY_COMPLETE_FEE_ADDRESS: "",
    STXCITY_TOKEN_DEPLOYMENT_FEE_ADDRESS: "",
    STXCITY_DEX_DEPLOYMENT_FEE_ADDRESS: "",
    BITFLOW_CORE_ADDRESS: "",
    BITFLOW_STX_TOKEN_ADDRESS: "",
    BITFLOW_FEE_ADDRESS: "",
  },
  mocknet: {
    BURN_ADDRESS: "",
    STXCITY_SWAP_FEE_ADDRESS: "",
    STXCITY_COMPLETE_FEE_ADDRESS: "",
    STXCITY_TOKEN_DEPLOYMENT_FEE_ADDRESS: "",
    STXCITY_DEX_DEPLOYMENT_FEE_ADDRESS: "",
    BITFLOW_CORE_ADDRESS: "",
    BITFLOW_STX_TOKEN_ADDRESS: "",
    BITFLOW_FEE_ADDRESS: "",
  }
};

export const TRAITS = {
  mainnet: {
    SIP010_FT:
      "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard.sip-010-trait",
    PROPOSAL:
      "SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.charisma-traits-v1.proposal-trait",
    EXTENSION:
      "SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.charisma-traits-v1.extension-trait",
    EXECUTOR: ".aibtcdev-traits-v1.executor-trait",
    TREASURY: ".aibtcdev-traits-v1.treasury-trait",
    PAYMENTS: ".aibtcdev-traits-v1.payments-trait",
    MESSAGING: ".aibtcdev-traits-v1.messaging-trait",
    BANK_ACCOUNT: ".aibtcdev-traits-v1.bank-account-trait",
    RESOURCE: ".aibtcdev-traits-v1.resource-trait",
    INVOICE: ".aibtcdev-traits-v1.invoice-trait",
    NFT: "SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.charisma-traits-v1.nft-trait",
    FT_PLUS:
      "SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.charisma-traits-v1.ft-plus-trait",
    SHARE_FEE_TO:
      "SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.charisma-traits-v1.share-fee-to-trait",
    BITFLOW_POOL: "SM1793C4R5PZ4NS4VQ4WMP7SKKYVH8JZEWSZ9HCCR.xyk-pool-trait-v-1-2.xyk-pool-trait",
    },
  testnet: {
    SIP010_FT:
      "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR.aibtcdev-traits-rc1.sip010-ft-trait",
    PROPOSAL:
      "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR.aibtcdev-traits-rc1.proposal-trait",
    EXTENSION:
      "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR.aibtcdev-traits-rc1.extension-trait",
    EXECUTOR:
      "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR.aibtcdev-traits-rc1.executor-trait",
    TREASURY:
      "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR.aibtcdev-traits-rc1.treasury-trait",
    PAYMENTS:
      "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR.aibtcdev-traits-rc1.payments-trait",
    MESSAGING:
      "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR.aibtcdev-traits-rc1.messaging-trait",
    BANK_ACCOUNT:
      "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR.aibtcdev-traits-rc1.bank-account-trait",
    RESOURCE:
      "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR.aibtcdev-traits-rc1.resource-trait",
    INVOICE:
      "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR.aibtcdev-traits-rc1.invoice-trait",
    NFT: "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR.aibtcdev-traits-rc1.nft-trait",
    FT_PLUS:
      "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR.aibtcdev-traits-rc1.ft-plus-trait",
    SHARE_FEE_TO:
      "ST2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2SYCBMRR.aibtcdev-traits-rc1.share-fee-to-trait",
  },
};
